AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

# For local testing:
# 1. Run test_workflow.sh to set up infrastructure
# 2. Run deploy_lambda.sh to deploy Lambda function
# 3. Run test_conversion.sh to test the workflow

Parameters:
  Environment:
    Type: String
    Default: local
    AllowedValues:
      - local
      - production
  DaskScheduler:
    Type: String
    Default: tcp://host.docker.internal:8786
    Description: Dask scheduler address

Conditions:
  IsLocal: !Equals [!Ref Environment, 'local']

Resources:
  NetCDFEventDispatcher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: handler.main
      Runtime: python3.11
      MemorySize: 2048
      Timeout: 900
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - !Sub arn:aws:s3:::${SOURCE_BUCKET_NAME}/*
                - !Sub arn:aws:s3:::${DEST_BUCKET_NAME}/*
      Layers:
        - !Ref DependencyLayer
      Environment:
        Variables:
          AWS_SAM_LOCAL: !Equals [!Ref Environment, 'local']
          AWS_REGION: !Sub '${AWS::Region}'
          QUEUE_URL: ${QUEUE_URL}
          SOURCE_BUCKET_NAME: ${SOURCE_BUCKET_NAME}
          DEST_BUCKET_NAME: ${DEST_BUCKET_NAME}
          SQS_ENDPOINT_URL: !If 
            - IsLocal
            - http://host.docker.internal:4566
            - ''
          DASK_SCHEDULER: !Ref DaskScheduler
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref SOURCE_BUCKET_NAME
            Events: s3:ObjectCreated:*

  DependencyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: netcdf-dependencies
      Description: Dependencies for NetCDF processing
      ContentUri: .aws-sam/deps/python
      CompatibleRuntimes:
        - python3.11 